### ISSUE TITLE
Why is var_dump in the production bundle?

### ISSUE THREAD

**Issue by toddheslin** [idleberg/php-vite-manifest#1]
https://github.com/idleberg/php-vite-manifest/blob/510728deb7162dffaf7a3a92a91152b49cade73f/src/ViteManifest.php#L100

**Comment by idleberg** [comment]
What a terrible oversight. Should be fixed in the new version. Thanks for pointing out!

**Comment by toddheslin** [comment]
All good, I found another problem with [php-wordpress-vite-assets](https://github.com/idleberg/php-wordpress-vite-assets) but I'll file an issue there. Thanks @idleberg !

**Comment by toddheslin** [comment]
Sorry, it was actually part of this repo — #2
