### ISSUE TITLE
Support for pracalculated file integrity hash on manifest file

### ISSUE THREAD

**Issue by chez14** [idleberg/php-vite-manifest#6]
Is it possible, if there's `integrity` key set on the manifest file, don't recalculate the hash again?

Plugin [`vite-plugin-manifest-sri`](https://www.npmjs.com/package/vite-plugin-manifest-sri) handles the `integrity` calculation on build, meaning the hash wont be calculated on each function call again which shorten the overhead to process the page request when hash is enabled.

Thanks!

**Comment by idleberg** [comment]
That sounds like a good idea. I will look into it once the bandage is removed off my dominant hand 😅

**Comment by idleberg** [comment]
Merged in https://github.com/idleberg/php-vite-manifest/pull/7
